#!/bin/bash

cd "$(dirname "$0")"

[ -n "$XILINX_SETTINGS_SCRIPT" ] && . "$XILINX_SETTINGS_SCRIPT"

if [ -z "$XILINX" -o ! -d "$XILINX" ] ; then
	echo "Please source the Xilinx settings script before calling this script." >&2
	exit 1
fi

[ -e "single-pendulum-vhdl.xise" ] || xtclsh single-pendulum-vhdl.tcl create_project

for ipcore in ../ipcore_dir/*.xco ; do
	coregen -b "$ipcore" -p ../ipcore_dir
done

xtclsh single-pendulum-vhdl.tcl run_process
