--------------------------------------------------------------------------------
--                          ParameterAssignmentTest
-- This wrapper has been generated by PivPav (using FloPoCo)
-- and is distributed under the terms of the GNU Lesser General Public Licence.
-- Authors: 
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity func is
  port (
    aclk : in std_logic;
    arg0_data : in std_logic_vector(31 downto 0);
    arg0_valid : in std_logic;
    arg0_ready : out std_logic;
    result_data : out std_logic_vector(31 downto 0);
    result_valid : out std_logic;
    result_ready : in std_logic
  );
end entity;

architecture behavioural of func is
begin
  func : process(aclk)
    variable result : integer;
  begin
    if rising_edge(aclk) then
      if arg0_valid = '1' then
        result := to_integer(signed(arg0_data)) * 3 + 1;
        result_data <= std_logic_vector(to_unsigned(result, result_data'length));
        result_valid <= '1';
      else
        result_data <= (others => '0');
        result_valid <= '0';
      end if;
    end if;
  end process;

  arg0_ready <= result_ready;
end architecture;
