--------------------------------------------------------------------------------
--                          ParameterAssignmentTest
-- This wrapper has been generated by PivPav (using FloPoCo)
-- and is distributed under the terms of the GNU Lesser General Public Licence.
-- Authors: 
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity func2 is
  port (
    aclk : in std_logic;
    arg0_data : in std_logic_vector(31 downto 0);
    arg0_valid : in std_logic;
    arg0_ready : out std_logic;
    arg1_data : in std_logic_vector(31 downto 0);
    arg1_valid : in std_logic;
    arg1_ready : out std_logic;
    done : out std_logic
  );
end entity;

architecture behavioural of func2 is
begin
  func2 : process(aclk)
    variable result : integer;
  begin
    if rising_edge(aclk) then
      if arg0_valid = '1' and arg1_valid = '1' then
        result := to_integer(signed(arg0_data)) * 3 + 1;
        done <= '1';
      else
        done <= '0';
      end if;
    end if;
  end process;

  arg0_ready <= '1';
  arg1_ready <= '1';
end architecture;
