#!/bin/sh
### BEGIN INIT INFO
# Provides:          mount
# Required-Start:    
# Required-Stop:     
# Order:             05
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mount filesystems
### END INIT INFO

if [ "$1" == "start" ] ; then
	echo -n "Mounting filesystems: "
	mount -a
	mkdir /dev/pts
	mount /dev/pts
	echo "."
fi
