#!/bin/sh
### BEGIN INIT INFO
# Provides:          syslog
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Order:             20
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: syslog
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=syslogd
DAEMON=/sbin/$NAME
DESC="syslog daemon"

# Check if DAEMON binary exist
test -f $DAEMON || exit 0

if [ -f "/etc/default/$NAME" ]; then
     . /etc/default/$NAME
fi

ARGS="-O /var/log/messages $SYSLOG_OPTIONS"

case "$1" in
  start)
    echo -n "Starting $DESC: "
    echo -n "$NAME"
    start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
      --exec $DAEMON > /dev/null 2>&1 -- $ARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    echo -n "$NAME"
    start-stop-daemon --retry 5 --oknodo --stop --quiet --pidfile /var/run/$NAME.pid \
      --exec $DAEMON  > /dev/null 2>&1
    echo "."
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
