--------------------------------------------------------------------------------
--                          ParameterAssignmentTest
-- This wrapper has been generated by PivPav (using FloPoCo)
-- and is distributed under the terms of the GNU Lesser General Public Licence.
-- Authors: 
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dummy_mod is
  port (
    aclk : in std_logic;
    arg0_data : in std_logic_vector(63 downto 0);
    arg0_valid : in std_logic;
    arg0_ready : out std_logic;
    arg1_data : in std_logic_vector(63 downto 0);
    arg1_valid : in std_logic;
    arg1_ready : out std_logic;
    result_data : out std_logic_vector(63 downto 0);
    result_valid : out std_logic;
    result_ready : in std_logic
  );
end entity;

architecture behavioural of dummy_mod is
begin
  dummy_mod : process(aclk)
    variable result : integer;
  begin
    if rising_edge(aclk) then
      if arg0_valid = '1' and arg1_valid = '1' then
        result_data <= arg0_data;
        result_valid <= '1';
      else
        result_data <= (others => '0');
        result_valid <= '0';
      end if;
    end if;
  end process;

  arg0_ready <= result_ready;
  arg1_ready <= result_ready;
end architecture;
