-- generated by Mehari
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.math_real.ALL;
use ieee.numeric_std.all;

library work;
use work.float_helpers.all;
use work.test_helpers.all;

entity test is
   port ( 
         aclk : in std_logic;
         reset : in std_logic;
         a_in_data : in  std_logic_vector(15 downto 0);
         a_in_valid : in std_logic;
         a_in_ready : out std_logic;
         return_data : out  std_logic_vector(31 downto 0);
         return_valid : out std_logic;
         return_ready : in std_logic
   );
end entity;

architecture arch of test is
signal t0_data :  std_logic_vector(31 downto 0);
signal t0_valid : std_logic;
signal t0_ready : std_logic;
begin
   t0_data <= "0000000000000000" & a_in_data;
   t0_valid <= a_in_valid;
   return_data <= t0_data;
   return_valid <= t0_valid;
   t0_ready <= return_ready;
   a_in_ready <= t0_ready;
end architecture;

