-- generated by Mehari
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
library work;

entity test is
   port ( 
         aclk : in std_logic;
         a_out_data : out  std_logic_vector(31 downto 0);
         a_out_valid : out std_logic;
         a_out_ready : in std_logic;
         b_out_data : out  std_logic_vector(31 downto 0);
         b_out_valid : out std_logic;
         b_out_ready : in std_logic
   );
end entity;

architecture arch of test is
begin
   a_out_data <= 1;
   a_out_valid <= '1';
   b_out_data <= 1;
   b_out_valid <= '1';
end architecture;

