-- generated by Mehari
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.math_real.ALL;
use ieee.numeric_std.all;

library work;
use work.float_helpers.all;
use work.test_helpers.all;

entity test is
   port ( 
         aclk : in std_logic;
         a_out_data : out  std_logic_vector(31 downto 0);
         a_out_valid : out std_logic;
         a_out_ready : in std_logic;
         b_out_data : out  std_logic_vector(31 downto 0);
         b_out_valid : out std_logic;
         b_out_ready : in std_logic
   );
end entity;

architecture arch of test is
begin
   a_out_data <= std_logic_vector(to_unsigned(1, 32));
   a_out_valid <= '1';
   b_out_data <= std_logic_vector(to_unsigned(1, 32));
   b_out_valid <= '1';
end architecture;

