#include "mehari/CodeGen/MyOperator.h"

MyOperator::MyOperator() : generateForTest(false) { }

void MyOperator::setTestMode() {
  generateForTest = true;
}

void MyOperator::licence(std::ostream& o, std::string authorsyears) {
  o<<"-- generated by Mehari"<<endl;
}

void MyOperator::stdLibs(std::ostream& o) {
  o << "library ieee;\n";
  o << "use ieee.std_logic_1164.all;\n";
  o << "use ieee.std_logic_unsigned.all;\n";
  o << "use ieee.math_real.ALL;\n";
  o << "use ieee.numeric_std.all;\n";
  o << "\n";

  if (generateForTest) {
    o << "library work;\n";
    o << "use work.float_helpers.all;\n";
    o << "use work.test_helpers.all;\n";
    o << "\n";
  } else {
    o << "library float_library_v1_00_a;\n";
    o << "use float_library_v1_00_a.float_helpers.all;\n";
    o << "\n";
  }
}
