#include "mehari/CodeGen/MyOperator.h"

void MyOperator::licence(std::ostream& o, std::string authorsyears) {
  o<<"-- generated by Mehari"<<endl;
}

void MyOperator::stdLibs(std::ostream& o) {
  o << "library ieee;\n";
  o << "use ieee.std_logic_1164.all;\n";
  o << "use ieee.std_logic_unsigned.all;\n";
  o << "use ieee.math_real.ALL;\n";
  o << "use ieee.numeric_std.all;\n";
  o << "\n";
  o << "library work;\n";
  o << "use work.float_helpers.all;\n";
  o << "use work.test_helpers.all;\n";
  o << "\n";
}
